import Head from 'next/head'
import React from 'react';
import { List, Card } from 'antd';

import styles from '../styles/Home.module.css'
const data = [
    {
        title: 'Title 1',
    },
    {
        title: 'Title 2',
    },
    {
        title: 'Title 3',
    },
    {
        title: 'Title 4',
    },
    {
        title: 'Title 5',
    },
    {
        title: 'Title 6',
    },
];
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Market</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
        <List
            grid={{
                gutter: 16,
                xs: 1,
                sm: 2,
                md: 4,
                lg: 4,
                xl: 6,
                xxl: 3,
            }}
            dataSource={data}
            renderItem={(item) => (
                <List.Item>
                    <Card title={item.title}>Card content</Card>
                </List.Item>
            )}
        />
    </div>
  )
}
